name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v3

     
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

     
      - name: Install dependencies
        run: npm install

    
      - name: Build application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
   
      - name: Checkout code
        uses: actions/checkout@v3

     
      - name: Deploy to server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 5.144.131.250 >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa sunflowe@5.144.131.250 "echo Connected!"
          rsync -avz ./build/ sunflowe@5.144.131.250:/var/www/project
